# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46b28202546f3b601bc3bb96b3371ee741cc83b5e3a58162f05a92493fe1926425d422352b79f27efd87b856e54432257599cc5da7aef7fb66f01c636590db2c

test:
  secret_key_base: 40cce17d4ccc0e62aafcf11ca12b0def4849b154606206e244bd942dbd45dabd3468ef6896490d994859c8f19d80d73ec9c1fb71dec99c43259cb369a000e4ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
